#!python
from setuptools import setup, find_packages

setup(name='z3c.zrtresource',
      version='0.1.1',
      author = "Zope Community",
      author_email = "zope3-dev@zope.org",
      description = open("README.txt").read(),
      license = "ZPL 2.1",
      keywords = "css resource zope zope3",
      url='http://svn.zope.org/z3c.zrtresource',
      extras_require = dict(test=['zope.app.testing',
                                  'zope.testing',
                                  'zope.traversing',
                                  ]),
      install_requires = ['setuptools',
                          'zope.app.component',
                          'zope.app.pagetemplate',
                          'zope.app.publisher',
                          'zope.component',
                          'zope.configuration',
                          'zope.interface',
                          'zope.publisher',
                          'zope.schema',
                          'zope.security',
                          ],
      zip_safe=False,
      packages=find_packages('src'),
      include_package_data=True,
      package_dir = {'':'src'},
      namespace_packages=['z3c',],
     )

